version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - myNetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks:
      - myNetwork
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/apps/weather-forecast
      - django_static_volume:/usr/src/apps/weather_forecast/static
    depends_on:
      - postgres
    env_file:
      - ./.env


volumes:
  django_static_volume:
  postgres_volume:

networks:
  myNetwork:
    driver: bridge